### ISSUE TITLE
Error Windows machine

### ISSUE THREAD

**Issue by trinker** [gaborcsardi/notifier#4]
Nice work.  Love the cross platform idea.

I get the following error:

![Imgur](http://i.imgur.com/b26GyCZ.png)

```
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] notifier_1.0.0         stansent_0.0.1         RSentiment_2.0         microbenchmark_1.4-2.1 sentimentr_0.3.0       syuzhet_1.0.0          meanr_0.1-0           
 [8] shortcut_1.0.0         plotflow_0.1.0         qdap_2.2.5             RColorBrewer_1.1-2     qdapRegex_0.7.0        qdapDictionaries_1.0.7 reports_0.3.0         
[15] qdapTools_1.3.2        pacman_0.4.1           scales_0.4.1           acc.roxygen2_0.1.1     devtools_1.11.0        roxygen2_5.0.1         ggplot2_2.2.0.9000    

loaded via a namespace (and not attached):
 [1] bitops_1.0-6         lubridate_1.5.6      httr_1.2.1           slidify_0.3.52       tools_3.2.4          R6_2.2.0             DBI_0.5-1            lazyeval_0.2.0      
 [9] colorspace_1.3-1     openNLPdata_1.5.3-2  withr_1.0.2          gridExtra_2.2.1      curl_2.2             git2r_0.14.0         chron_2.3-47         XLConnect_0.2-11    
[17] textshape_0.1.1      NLP_0.1-9            sandwich_2.3-4       slam_0.1-35          mvtnorm_1.0-5        tm_0.6-2             stringr_1.1.0        digest_0.6.10       
[25] bibtex_0.4.0         plotrix_3.6-1        BiocInstaller_1.20.2 zoo_1.7-13           openNLP_0.2-6        gtools_3.5.0         dplyr_0.5.0          xlsx_0.5.7          
[33] XLConnectJars_0.2-9  RCurl_1.95-4.8       magrittr_1.5         wordcloud_2.5        Rcpp_0.12.8          munsell_0.4.3        RefManageR_0.10.13   stringi_1.1.2       
[41] multcomp_1.4-4       whisker_0.3-2        yaml_2.1.13          MASS_7.3-45          RJSONIO_1.3-0        plyr_1.8.4           grid_3.2.4           parallel_3.2.4      
[49] gdata_2.17.0         gender_0.5.1         lattice_0.20-33      splines_3.2.4        xlsxjars_0.6.1       knitr_1.13           venneuler_1.1-0      igraph_1.0.1        
[57] markdown_0.7.7       reshape2_1.4.2       codetools_0.2-14     XML_3.98-1.4         data.table_1.9.6     gtable_0.2.0         assertthat_0.1       survival_2.38-3     
[65] tibble_1.2           rJava_0.9-8          memoise_1.0.0        knitcitations_1.0.7  TH.data_1.0-7       
> 

```

**Comment by gaborcsardi** [comment]
Right, it seems that that executable needs some DLLs on the system. I'll try to make an .exe that includes the required DLLs.

**Comment by gaborcsardi** [comment]
Can you give it another try? Unfortunately I cannot try it on a virgin windows 8 machine right now. All the machines I have access to have .NET and a bunch of other dev tools installed...

The windows installation is also not very smooth, I realized. :/ #5

**Comment by trinker** [comment]
Sorry same result.

**Comment by dpastoor** [comment]
@gaborcsardi don't know if it would be better to make a separate issue as this is a different error, however will post here for now to keep windows issues in one place until you want to move them:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.WindowsAPICodePack, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at toast.Program.InstallShortcut(String shortcutPath)
   at toast.Program.TryCreateShortcut()
   at toast.Program.Main(String[] args)
Warning message:
running command '"C:/Program Files/R/R-3.3.2/library/notifier/toaster/toast.exe" -m "hello" -t "there" -p "C:\Program Files\R\R-3.3.2\library\notifier\R.png"' had status 255 
```


session info:

```
> devtools::session_info()
Session info -----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-12-04                  

Packages ---------------------------------------------------------------------------------
 package  * version date       source                               
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.2)                       
 digest     0.6.10  2016-08-02 CRAN (R 3.3.2)                       
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.2)                       
 notifier * 1.0.0   2016-12-04 Github (gaborcsardi/notifier@66d2666)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)           
```

windows version pulled from sessionInfo(): `Running under: Windows >= 8 x64 (build 9200)` (windows 10 insider preview)

**Comment by gaborcsardi** [comment]
@dpastoor Yes, same issue.

**Comment by gaborcsardi** [comment]
OK, I tried it this time on a virgin windows 8 N install, it should work. Please reopen if you still have problems.

**Comment by trinker** [comment]
Success.  Thank you :-)
